version: '3'

services:
  stanfordcorenlp:
    image: anwala/stanfordcorenlp
    #restart: always
  grapher:
    image: storygraph-grapher:latest
    #restart: always
    build:
      context: .
    command: './genStoryGraph.py stanfordcorenlp'
    volumes:
      - /data/anwala/IMLS/StoryGraph:/data
